Map<String,String> english = {
  'CNP_PageTitle' : 'Create Note',
  'CNP_TextBoxTitle' : 'Title is Here',
  'CNP_TextBoxNote' : 'Note is Here',
  'CNP_STRnewnote' : 'New note',
  'CNP_ALERTsneakbar' : 'Please upgrade your license !',
  'CNP_BTNcreateNewNote' : 'Create a new note',
  'HP_PageTitle' : 'Your Notes',
  'HP_hellobar' : 'Hello ,',
  'HP_AlertBoxTitle' : 'Delete ?',
  'HP_AlertBoxDetails' : 'Are you sure you want to delete ;',
  'HP_AlertBoxButton1' : 'Cancel',
  'HP_AlertBoxButton2' : 'Apply',
  'HP_STRnonstream' : 'You do not have a Note\n\nTry Create a new Note',
  'HP_strDelete' : 'Delete',
  'HP_strEdit' : 'Edit',
  'HP_strLeftToRight' : 'Swipe Right',
  'UP_PageTitle' : 'Your Profile',
  'UP_strGM' : 'Good Morning',
  'UP_strGA' : 'Good afternoon',
  'UP_strGE' : 'Good Evening',
  'UP_BTNlogout' : 'Logout',
  'UP_strPlan' : 'Your Plan',
  'UP_strChangePlan' : 'Change Plan',
  'UP_P1title' : 'Free / LifeTime',
  'UP_P1details1' : '-Max 6 note',
  'UP_P1details2' : '-Max 1024 characters',
  'UP_P2title' : '\$0.30 / Month',
  'UP_P2details1' : '-Max 12 note',
  'UP_P2details2' : '-Max 1024 characters',
  'UP_P3title' : '\$0.60 / Month',
  'UP_P3details1' : '-Max 24 note',
  'UP_P3details2' : '-Max 1024 characters',
  'UP_P4title' : ' \$0.90 / Month',
  'UP_P4details1' : '-Max 36 note',
  'UP_P4details2' : '-Max 2048 characters',
  'UP_P1footer' : '*Default Plan*',
  'UP_P234footer' : '*Buy For Click me*',
  'UP_strChangeLanguage' : 'Change Language',
  'UP_btnCT' : 'Change Theme',
  'UP_btnBlc' : 'Black',
  'UP_btnLig' : 'Light',
  'SNP_PageTitle' : 'Edit Note',
  'SNP_strTitle' : 'Title is Here',
  'SNP_strNote' : 'Note is Here',
  'SNP_ALERTsneakbar' : 'Saving ...',
  'SNP_BTNsave' : 'Save',
  'S_NP' : 'Notes Page',
  'S_UP' : 'User Page',
  'L_btnStr' : 'Login with Google Account',
  'L_altStr' : 'Login For Continue',
  'L_author' : 'Developed by Furkan Ulgen',
};
Map<String,String> turkish = {
  'CNP_PageTitle' : 'Not Oluştur',
  'CNP_TextBoxTitle' : 'Başlık Buraya',
  'CNP_TextBoxNote' : 'Not Buraya',
  'CNP_STRnewnote' : 'Yeni Not',
  'CNP_ALERTsneakbar' : 'Lütfen Lisansınızı Yükseltin !',
  'CNP_BTNcreateNewNote' : 'Yeni Not Oluşturma',
  'HP_PageTitle' : 'Notların',
  'HP_hellobar' : 'Merhaba ,',
  'HP_AlertBoxTitle' : 'Silmek ?',
  'HP_AlertBoxDetails' : 'Silmek İstediğine Eminmisin ? ;',
  'HP_AlertBoxButton1' : 'İptal',
  'HP_AlertBoxButton2' : 'Evet',
  'HP_STRnonstream' : 'Hiç Notun Yok\n\nHemen Oluştur',
  'HP_strDelete' : 'Sil',
  'HP_strEdit' : 'Düzenle',
  'HP_strLeftToRight' : 'Sağa Kaydır',
  'UP_PageTitle' : 'Profilin',
  'UP_strGM' : 'Günaydın',
  'UP_strGA' : 'Tünaydın',
  'UP_strGE' : 'İyi Geceler',
  'UP_BTNlogout' : 'Çıkış',
  'UP_strPlan' : 'Planın',
  'UP_strChangePlan' : 'Planını Değiştir',
  'UP_P1title' : 'Bedava / Ömür Boyu',
  'UP_P1details1' : '-En fazla 6 not',
  'UP_P1details2' : '-En fazla 1024 karakter',
  'UP_P2title' : '\$0.30 / Aylık',
  'UP_P2details1' : '-En fazla 12 not',
  'UP_P2details2' : '-En fazla 1024 karakter',
  'UP_P3title' : '\$0.60 / Aylık',
  'UP_P3details1' : '-En fazla 24 not',
  'UP_P3details2' : '-En fazla 1024 karakter',
  'UP_P4title' : ' \$0.90 / Aylık',
  'UP_P4details1' : '-En fazla 36 not',
  'UP_P4details2' : '-En fazla 2048 karakter',
  'UP_P1footer' : '*Varsayılan*',
  'UP_P234footer' : '*Satın almak için tıkla*',
  'UP_strChangeLanguage' : 'Dil Değiştir',
  'UP_btnCT' : 'Renk Değiştir',
  'UP_btnBlc' : 'Siyah',
  'UP_btnLig' : 'Aydınlık',
  'SNP_PageTitle' : 'Notu Düzenle',
  'SNP_strTitle' : 'Burası Başlık',
  'SNP_strNote' : 'Burası Not',
  'SNP_ALERTsneakbar' : 'Kayıt Ediliyor ...',
  'SNP_BTNsave' : 'Kayıt Et',
  'S_NP' : 'Notlar',
  'S_UP' : 'Profil',
  'L_btnStr' : 'Google İle Giriş Yap',
  'L_altStr' : 'Devam Etmek İçin Giris Yap',
  'L_author' : 'Furkan Ulgen Tarafından Geliştirildi.',
};
Map<String,String> russain = {
  'CNP_PageTitle' : 'создать заметку',
  'CNP_TextBoxTitle' : 'Название здесь',
  'CNP_TextBoxNote' : 'Примечание здесь',
  'CNP_STRnewnote' : 'Новая заметка',
  'CNP_ALERTsneakbar' : 'Пожалуйста, обновите вашу лицензию!',
  'CNP_BTNcreateNewNote' : 'Создание новой заметки',
  'HP_PageTitle' : 'ваши заметки',
  'HP_hellobar' : 'Привет ,',
  'HP_AlertBoxTitle' : 'Удалить ?',
  'HP_AlertBoxDetails' : 'Вы уверены, что хотите удалить? ;',
  'HP_AlertBoxButton1' : 'Отмена',
  'HP_AlertBoxButton2' : 'Да',
  'HP_STRnonstream' : 'У вас нет заметок\n\nСоздать сейчас',
  'HP_strDelete' : 'Удалить',
  'HP_strEdit' : 'Редактировать',
  'HP_strLeftToRight' : 'Проведите вправо',
  'UP_PageTitle' : 'Ваш профиль',
  'UP_strGM' : 'Доброе утро',
  'UP_strGA' : 'Добрый день',
  'UP_strGE' : 'Доброй ночи',
  'UP_BTNlogout' : 'Выход',
  'UP_strPlan' : 'Ваш план',
  'UP_strChangePlan' : 'Измените свой план',
  'UP_P1title' : 'Бесплатно / пожизненно',
  'UP_P1details1' : '-До 6 заметок',
  'UP_P1details2' : '-До 1024 символов',
  'UP_P2title' : '\$0.30 / Ежемесячно',
  'UP_P2details1' : '-До 12 заметок',
  'UP_P2details2' : '-До 1024 символов',
  'UP_P3title' : '\$0.60 / Ежемесячно',
  'UP_P3details1' : '-До 24 заметок',
  'UP_P3details2' : '-До 1024 символов',
  'UP_P4title' : ' \$0.90 / Ежемесячно',
  'UP_P4details1' : '-До 36 заметок',
  'UP_P4details2' : '-До 2048 символов',
  'UP_P1footer' : '*умолчанию*',
  'UP_P234footer' : '*Нажмите, чтобы купить*',
  'UP_strChangeLanguage' : 'изменение языка',
  'UP_btnCT' : 'Поменять тему',
  'UP_btnBlc' : 'Черный',
  'UP_btnLig' : 'Легкий',
  'SNP_PageTitle' : 'Изменить примечание',
  'SNP_strTitle' : 'Это название',
  'SNP_strNote' : 'Это примечание',
  'SNP_ALERTsneakbar' : 'Регистрация...',
  'SNP_BTNsave' : 'Запиши это',
  'S_NP' : 'Заметки',
  'S_UP' : 'Профиль',
  'L_btnStr' : 'Войти через Google',
  'L_altStr' : 'Войдите, чтобы продолжить',
  'L_author' : 'Разработан Furkan Ulgen',
};
Map<String,String> german = {
  'CNP_PageTitle' : 'Schaffen',
  'CNP_TextBoxTitle' : 'Titel hier',
  'CNP_TextBoxNote' : 'Hinweis hier',
  'CNP_STRnewnote' : 'Neue Anmerkung',
  'CNP_ALERTsneakbar' : 'Bitte aktualisieren Sie Ihre Lizenz!',
  'CNP_BTNcreateNewNote' : 'Neue Notiz erstellen',
  'HP_PageTitle' : 'deine Noten',
  'HP_hellobar' : 'Hallo ,',
  'HP_AlertBoxTitle' : 'Löschen ?',
  'HP_AlertBoxDetails' : 'Sind Sie sicher, dass Sie löschen möchten ? ;',
  'HP_AlertBoxButton1' : 'İptal',
  'HP_AlertBoxButton2' : 'Evet',
  'HP_STRnonstream' : 'Sie haben keine Notizen\n\nJetzt erstellen',
  'HP_strDelete' : 'Löschen',
  'HP_strEdit' : 'Bearbeiten',
  'HP_strLeftToRight' : 'Wische nach rechts',
  'UP_PageTitle' : 'Dein Profil',
  'UP_strGM' : 'Guten Morgen',
  'UP_strGA' : 'Guten Nachmittag',
  'UP_strGE' : 'Gute Nacht',
  'UP_BTNlogout' : 'Ausgang',
  'UP_strPlan' : 'Dein Plan',
  'UP_strChangePlan' : 'Ändern Sie Ihren Plan',
  'UP_P1title' : 'Kostenlos / Lebenslang',
  'UP_P1details1' : '-Bis zu 6 Noten',
  'UP_P1details2' : '-bis zu 1024 Zeichen',
  'UP_P2title' : '\$0.30 / Monatlich',
  'UP_P2details1' : '-Bis zu 12 Noten',
  'UP_P2details2' : '-bis zu 1024 Zeichen',
  'UP_P3title' : '\$0.60 / Monatlich',
  'UP_P3details1' : '-Bis zu 24 Noten',
  'UP_P3details2' : '-bis zu 1024 Zeichen',
  'UP_P4title' : ' \$0.90 / Monatlich',
  'UP_P4details1' : '-Bis zu 36 Noten',
  'UP_P4details2' : '-bis zu 2048 Zeichen',
  'UP_P1footer' : '*Standard*',
  'UP_P234footer' : '*Klicken um zu kaufen*',
  'UP_strChangeLanguage' : 'Sprache ändern',
  'UP_btnCT' : 'Thema ändern',
  'UP_btnBlc' : 'Schwarz',
  'UP_btnLig' : 'Licht',
  'SNP_PageTitle' : 'Notiz bearbeiten',
  'SNP_strTitle' : 'Dies ist der Titel',
  'SNP_strNote' : 'Dies ist die Notiz',
  'SNP_ALERTsneakbar' : 'Registrieren ...',
  'SNP_BTNsave' : 'sparen',
  'S_NP' : 'Anmerkungen',
  'S_UP' : 'Profil',
  'L_btnStr' : 'Anmeldung mit Google',
  'L_altStr' : 'Melden Sie sich an, um fortzufahren',
  'L_author' : 'Entwickelt von Furkan Ulgen.',
};